### ISSUE TITLE
Spinning service instances fail - maybe only related to v1 instances

### ISSUE THREAD

**Issue by alexanderheckel** [Juniper/contrail-ansible-deployer#21]
config/instances.yaml
```
provider_config:
  bms:
    ssh_pwd: contrail123
    ssh_user: root
    domainsuffix: local
    ntpserver: de.pool.ntp.org
instances:
  bms1:
    provider: bms
    ip: 10.10.10.11
    roles:
      openstack:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
  bms2:
    provider: bms
    ip: 10.10.10.12
    roles:
      openstack_compute:
      vrouter:
        VROUTER_GATEWAY: 10.10.10.1
  bms3:
    provider: bms
    ip: 10.10.10.13
    roles:
      openstack_compute:
      vrouter:
        VROUTER_GATEWAY: 10.10.10.1
contrail_configuration:
  RABBITMQ_NODE_PORT: 5673
  KEYSTONE_AUTH_URL_VERSION: /v3
  AUTH_MODE: keystone
kolla_config:
  customize:
    nova.conf: |
      [libvirt]
      virt_type=qemu
      cpu_mode=none
  kolla_globals:
    kolla_internal_vip_address: 10.10.10.11
    kolla_external_vip_address: 10.10.10.11
    enable_haproxy: "no"
    enable_ironic: "no"
    enable_swift: "no"
```

Docker Repository and Version: opencontrailnightly / master-115

Issue:

When trying to start/spin the analyzer image (fresh installation, user admin) I'm getting the following error:

```
05/24/2018 12:21:24 PM [contrail-svc-monitor]: __default__ [SYS_ERR]: SvcMonitorLog: nova error The request you have made requires authentication. (HTTP 401) (Request-ID: req-902fd9cc-4cc6-448a-a948-1f4f55b34d64)  
05/24/2018 12:21:24 PM [contrail-svc-monitor]: __default__ [SYS_ERR]: SvcMonitorLog: Flavor not found default-domain:analyzer-template
```

m1.medium flavor is available:
```
[root@controller-1 ~]# openstack flavor list
+--------------------------------------+-----------+------+------+-----------+-------+-----------+
| ID                                   | Name      |  RAM | Disk | Ephemeral | VCPUs | Is Public |
+--------------------------------------+-----------+------+------+-----------+-------+-----------+
| 245db933-cab7-4eb7-95fa-7aed9d59f5f1 | m1.tiny   |  512 |    1 |         0 |     1 | True      |
| a3a6bd2a-1e3b-4c66-9ea9-e0add09964af | m1.small  | 2048 |   20 |         0 |     1 | True      |
| d8b5fd1e-69a9-4030-8e70-d5e6d1f577a9 | m1.medium | 4096 |   40 |         0 |     2 | True      |
+--------------------------------------+-----------+------+------+-----------+-------+-----------+
```

analyzer-vm-console-qcow2 image is available:

```
[root@controller-1 ~]# openstack image list
+--------------------------------------+----------+--------+
| ID                                   | Name     | Status |
+--------------------------------------+----------+--------+
| add2e564-8e63-4851-a047-7a16fbeab015 | analyzer | active |
| 839ce2de-d201-4c68-95ff-f789ebf90788 | cirros2  | active |
+--------------------------------------+----------+--------+
```

/etc/contrail/contrail-keystone-auth.conf:
```
[KEYSTONE]
#memcache_servers=127.0.0.1:11211
admin_password = contrail123
admin_tenant_name = admin
admin_user = admin
auth_host = 10.10.10.11
auth_port = 35357
auth_protocol = http
auth_url = http://10.10.10.11:35357/v3
auth_type = password
user_domain_name = Default
project_domain_name = Default
region_name = RegionOne
```

/etc/contrail/contrail-svc-monitor.conf
```
[DEFAULTS]
api_server_ip=10.10.10.11
api_server_port=8082
log_file=/var/log/contrail/contrail-svc-monitor.log
log_level=SYS_NOTICE
log_local=1
cassandra_server_list=10.10.10.11:9161
zk_server_ip=10.10.10.11:2181

rabbit_server=10.10.10.11:5673
rabbit_vhost=/
rabbit_user=guest
rabbit_password=guest
rabbit_use_ssl=False


collectors=10.10.10.11:8086

[SECURITY]
use_certs=False
keyfile=/etc/contrail/ssl/private/server-privkey.pem
certfile=/etc/contrail/ssl/certs/server.pem
ca_certs=/etc/contrail/ssl/certs/ca-cert.pem

[SCHEDULER]
# Analytics server list used to get vrouter status and schedule service instance
analytics_server_list=10.10.10.11:8081
aaa_mode = no-auth

[SANDESH]
introspect_ssl_enable=False
sandesh_ssl_enable=False
```

Btw.: Any attempt spinning v1 service templates does not work.
