### ISSUE TITLE
Derived / prepared contrail-vrouter-agent.conf faulty

### ISSUE THREAD

**Issue by alexanderheckel** [Juniper/contrail-ansible-deployer#22]
Repository: opencontrailnightly
Version: at least master-115 and master-117

```
[root@controller-1 ~]# cat contrail-ansible-deployer/config/instances.yaml
provider_config:
  bms:
    ssh_pwd: contrail123
    ssh_user: root
    domainsuffix: local
    ntpserver: de.pool.ntp.org
instances:
  bms1:
    provider: bms
    ip: 10.10.10.11
    roles:
      openstack:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      vrouter:
        VROUTER_GATEWAY: 10.10.10.1
  bms2:
    provider: bms
    ip: 10.10.10.12
    roles:
      openstack_compute:
      vrouter:
        VROUTER_GATEWAY: 10.10.10.1
  bms3:
    provider: bms
    ip: 10.10.10.13
    roles:
      openstack_compute:
      vrouter:
        VROUTER_GATEWAY: 10.10.10.1
contrail_configuration:
  #CONTAINER_REGISTRY: opencontrailnightly
  #CONTRAIL_VERSION: master-112
  #CONTRAIL_VERSION: master-115
  RABBITMQ_NODE_PORT: 5673
  KEYSTONE_AUTH_URL_VERSION: /v3
  AUTH_MODE: keystone
  #UPGRADE_KERNEL: true
kolla_config:
  customize:
    nova.conf: |
      [libvirt]
      virt_type=qemu
      cpu_mode=none
  kolla_globals:
    kolla_internal_vip_address: 10.10.10.11
    kolla_external_vip_address: 10.10.10.11
    enable_haproxy: "no"
    enable_ironic: "no"
    enable_swift: "no"
```

When trying to deploy a seperate vRouter (kind of (physical) network gateway) the docker container restarts/crashes endlessly.

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_config_file_syntax> >'
  what():  the options configuration file contains an invalid line '10.10.10.1'
```

Line 3 ("10.10.10.1/24") and 7 ("10.10.10.1") of the section "[VIRTUAL-HOST-INTERFACE]" of the (derived?) configuration in /etc/contrail/contrail-vrouter-agent.conf seems to be the issue:

```
[VIRTUAL-HOST-INTERFACE]
name=vhost0
ip=10.10.10.11/24
10.10.10.1/24
physical_interface=vxlan0
gateway=10.10.10.1
compute_node_address=10.10.10.11/24
10.10.10.1
```

However the problem does not occure when role openstack_compute is deployed as well - the faulty entries are missing then and the container starts properly.

I'm not sure if this is related to the deployer or the container repo / team.
